services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./www:/var/www/html              # Carpeta pública
      - ./moodledata:/var/www/moodledata  # Carpeta privada
      - ./apache_logs:/var/log/apache2    # Logs de Apache

    environment:
      # Puedes agregar variables de entorno si las necesitas
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d"


  db:
    image: mysql:8.4.6
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - db
    restart: unless-stopped
    environment:
      PMA_HOST: db

